server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''

  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    activate:
      on-profile: prod

build.version: "3.0"

accounts:
  message: "Welcome in RND on Accounts related API's in PROD env"
  contactDetails:
    name: "Shivika Singh"
    email: "shivika@gmail.com"
  onCallSupport:
    -(91) 666-888
    -(91) 888-777

